<?php

/**
 * Blog
 * 
 * @author    Kanat Gailimov <gailimov@gmail.com>
 * @copyright Copyright (c) 2011 Kanat Gailimov, (http://gailimov.info)
 */


namespace Projects\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Get by slug
     * 
     * @param  string $slug Slug
     * @return array
     */
    public function getBySlug($slug)
    {
        $query = "SELECT c
                  FROM ProjectsBlogBundle:Category c
                  WHERE c.slug = ?1";

        try {
            return $this->getEntityManager()->createQuery($query)
                                            ->setParameter(1, $slug)
                                            ->getSingleResult();
        } catch(NoResultException $e) {
            return null;
        }
    }
}
