<?php

/**
 * Blog
 * 
 * @author    Kanat Gailimov <gailimov@gmail.com>
 * @copyright Copyright (c) 2011 Kanat Gailimov, (http://gailimov.info)
 */


namespace Projects\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * Get approved
     * 
     * @param  integer $num Number
     * @return array
     */
    public function getAllApproved($num)
    {
        $query = "SELECT c
                  FROM ProjectsBlogBundle:Comment c
                  WHERE c.approved = 1
                  ORDER BY c.createdAt DESC, c.id DESC";

        try {
            return $this->getEntityManager()->createQuery($query)
                                            ->setMaxResults($num)
                                            ->getResult();
        } catch(NoResultException $e) {
            return false;
        }
    }
}
