<?php

/**
 * Blog
 * 
 * @author    Kanat Gailimov <gailimov@gmail.com>
 * @copyright Copyright (c) 2011 Kanat Gailimov, (http://gailimov.info)
 */


namespace Projects\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * Get by post ID
     * 
     * @param  integer $postId ID of post
     * @return array
     */
    public function getByPostId($postId)
    {
        $query = "SELECT c
                  FROM ProjectsBlogBundle:Comment c
                  WHERE c.postId = ?1
                  AND c.approved = 1";

        try {
            return $this->getEntityManager()->createQuery($query)
                                            ->setParameter(1, $postId)
                                            ->getResult();
        } catch(NoResultException $e) {
            return null;
        }
    }
}
