<?php

/**
 * Blog
 * 
 * @author    Kanat Gailimov <gailimov@gmail.com>
 * @copyright Copyright (c) 2011 Kanat Gailimov, (http://gailimov.info)
 */


namespace Projects\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    /**
     * Get
     * 
     * @return array
     */
    public function get()
    {
        $query = "SELECT c
                  FROM ProjectsBlogBundle:Config c";

        return $this->getEntityManager()->createQuery($query)
                                        ->getSingleResult();
    }
}
