<?php

/**
 * Blog
 * 
 * @author    Kanat Gailimov <gailimov@gmail.com>
 * @copyright Copyright (c) 2011 Kanat Gailimov, (http://gailimov.info)
 */


namespace Projects\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    /**
     * Find all
     * 
     * @return array
     */
    public function findAll()
    {
        $query = "SELECT l
                  FROM ProjectsBlogBundle:Link l";

        return $this->getEntityManager()->createQuery($query)
                                        ->getResult();
    }
}
