<?php

/**
 * Blog
 * 
 * @author    Kanat Gailimov <gailimov@gmail.com>
 * @copyright Copyright (c) 2011 Kanat Gailimov, (http://gailimov.info)
 */


namespace Projects\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Get by username
     * 
     * @param  string $username Username
     * @return array
     */
    public function getByUsername($username)
    {
        $query = "SELECT u
                  FROM ProjectsBlogBundle:User u
                  WHERE u.username = ?1";

        try {
            return $this->getEntityManager()->createQuery($query)
                                            ->setParameter(1, $username)
                                            ->getSingleResult();
        } catch(NoResultException $e) {
            return null;
        }
    }

    /**
     * Get admin
     * 
     * @return array
     */
    public function getAdmin()
    {
        $query = "SELECT u
                  FROM ProjectsBlogBundle:User u
                  WHERE u.username = 'admin'";

        return $this->getEntityManager()->createQuery($query)
                                        ->getSingleResult();
    }
}
