<?php

/**
 * Blog
 * 
 * @author    Kanat Gailimov <gailimov@gmail.com>
 * @copyright Copyright (c) 2011 Kanat Gailimov, (http://gailimov.info)
 */


namespace Projects\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Get admin
     * 
     * @return array
     */
    public function getAdmin()
    {
        $query = "SELECT u
                  FROM ProjectsBlogBundle:User u
                  WHERE u.username = 'admin'";

        return $this->getEntityManager()->createQuery($query)
                                        ->getSingleResult();
    }
}
